version: '3'
services:
  watchdog:
    image: golang:1.19
    environment:
      SMTP_FROM_EMAIL: SMTP_FROM_EMAIL  # 送信元のメールアドレス
      SMTP_TO_EMAIL: SMTP_TO_EMAIL  # 送信先のメールアドレス
      SMTP_SERVER: SMTP_SERVER  # SMTPサーバのアドレス
      SMTP_PORT: "SMTP_PORT"  # SMTPサーバのポート
      SMTP_PASSWORD: SMTP_PASSWORD  # SMTPサーバのパスワード
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    working_dir: /app
    command: go run main.go
